### ISSUE TITLE
Message: docx2hub error on unzipping.

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2tex#1] opened 2015-06-19 12:05 UTC
Message: docx2hub error on unzipping.
Zip file seems to be corrupted: /infektionen-bei-haematologischen-und-onkologischen-patienten-uebersicht.docx (No such file or directory)

ERROR: err:XD0001:Only whitespace text nodes can appear at the top level in a document
ERROR: err:XD0001:Only whitespace text nodes can appear at the top level in a document
ERROR: err:XD0001:Only whitespace text nodes can appear at the top level in a document
ERROR: It is a dynamic error if a non-XML resource is produced on a step output or arrives on a step input.

I can provide the sample file by email since Github does not support DOCX uploads.

The issue appears to be specific to MacOSX. Converting the same file on Linux works.

**Comment by gimsieke** [comment] 2015-06-19 12:09
What’s the full path of the file? I isn’t /infektionen-bei-haematologischen-und-onkologischen-patienten-uebersicht.docx, is it?

**Comment by zopyx** [comment] 2015-06-19 12:15
The problem seems to be that the conversion does not deal with relative paths properly. 
Using absolute paths seems to work.

**Comment by gimsieke** [comment] 2015-06-19 12:24
It might try to resolve relative paths with with respect to the front end script. Can you disclose you setup? OS (= Mac OS X?), cwd, full invocation cmd line? If the issue it isn’t obvious to us, we’ll get hold of a Mac next week and reproduce&fix it. Thanks for reporting this issue!

**Comment by zopyx** [comment] 2015-06-19 12:28
./d2t ../some.docx

on MacOSX caused on failure

and this failed on Linux

[ajung@dev1 docx2text]$ ./d2t lungenkarzinom-nicht-kleinzellig-nsclc.docx
starting docx2tex
Errors encountered while running docx2tex. Please see
/home/ajung/src/docx2text/lungenkarzinom-nicht-kleinzellig-nsclc.log for
details.

2015-06-19 14:24 GMT+02:00 Gerrit Imsieke <notifications@github.com>:

**Comment by gimsieke** [comment] 2015-06-19 12:38
Maybe related to the [real_dir()](https://github.com/transpect/docx2tex/blob/master/d2t#L24) bash function that Jim Fuller and I devised as a replacement for `readlink -f` that’s missing on vanilla Mac installations. But maybe also an error of the [tr:file-uri](https://github.com/transpect/xproc-util/blob/master/file-uri/xpl/file-uri.xpl) step that @mkraetke forked from [svn](https://subversion.le-tex.de/common/xproc-util/file-uri/file-uri.xpl) (also: [letex:uri-composer()](https://subversion.le-tex.de/common/letex-util/resolve-uri/resolve-uri.xsl)) where I committed some fixes in the meantime. 

@mkraetke, please check whether the github version matches the current svn version.

@zopyx: We haven’t migrated every transpect related stuff to github yet. Some libraries currently exist on our svn and on github, some only on svn.

**Comment by zopyx** [comment] 2015-06-19 12:56
That's why am testing and poking you :-)

**Comment by mkraetke** [comment] 2015-06-19 13:24
OK, I've tested with some DOCX files on OSX and they worked. Your file converts well on Windows and Linux, but I can reproduce the error with Mac OSX. I hope I can figure out the bug and fix it soon.

**Comment by mkraetke** [comment] 2015-06-19 16:01
The bug is now fixed and was caused by an older bug in our URI resolver module, that was not yet fixed in our GitHub repository. Unfortunately, the GitHub repositories are currently a bit older than their SVN counterparts. Reminds me that we should move soon the other modules completely to GitHub.

Thank you for your valuable bug report!

**Closed by mkraetke** 2015-06-19 16:01 UTC
