### ISSUE TITLE
! Undefined control sequence.

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2tex#12] opened 2015-09-27 20:21 UTC
(/opt/local/share/texmf-texlive/tex/latex/latexconfig/epstopdf-sys.cfg))
(/opt/local/share/texmf-texlive/tex/latex/hyperref/nameref.sty
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/gettitlestring.sty))
Chapter 1.
! Undefined control sequence.
l.37 ...den Sie daf\"{u}r die Formatvorlage {\glqq
                                                  }\"{U}berschrift 1{\grqq}.

I can send you the related DOCX file by private email.

**Comment by zopyx** [comment] 2015-09-27 20:22
(/opt/local/share/texmf-texlive/tex/latex/latexconfig/epstopdf-sys.cfg))
(/opt/local/share/texmf-texlive/tex/latex/hyperref/nameref.sty
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/gettitlestring.sty))
Chapter 1.
! Undefined control sequence.
l.37 ...den Sie daf\"{u}r die Formatvorlage {\glqq
                                                  }\"{U}berschrift 1{\grqq}.

**Comment by mkraetke** [comment] 2015-10-05 06:50
This bug seems to be a duplicate of Bug #10 where the babel package was missing. @lwittmar fixed this already with commit e7b31a51481307f59bae269723e07c6dab0afc4a.

**Closed by mkraetke** 2015-10-05 06:50 UTC
